document.writeln("<!DOCTYPE html PUBLIC \'-//W3C//DTD XHTML 1.0 Transitional//EN\' \'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\'>");
document.writeln("<html xmlns=\'http://www.w3.org/1999/xhtml\'>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\' />");
document.writeln("<title>无标题文档</title>");
document.writeln("<link rel=\'stylesheet\' href=\'css/common.css\' />");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<div class=\'footer\'>");
document.writeln("	<div class=\'footerNew\'>");
document.writeln("    	<div class=\'weima\'>");
document.writeln("        	<h5>手机扫描二维码：</h5>");
document.writeln("            <img src=\'image/Android_ico_d.gif\' />");
document.writeln("            <img src=\'image/iphone_ico_d.gif\' />");
document.writeln("        </div>");
document.writeln("        <div class=\'footer_tel\'>");
document.writeln("        	<p>客服热线</p>");
document.writeln("            <p><span>12345679812</span></p>");
document.writeln("            <p>配送时间</p>");
document.writeln("            <p><span>09：00~22:00</span></p>");
document.writeln("            <p>谢谢配合</p>");
document.writeln("        </div>");
document.writeln("        <div class=\'footer_ul\'>");
document.writeln("        	<ul>");
document.writeln("            	<span>配送支付</span>");
document.writeln("                <li><a href=\'#\'>支付方式</a>");
document.writeln("                <li><a href=\'#\'>配送方式</a>");
document.writeln("                <li><a href=\'#\'>配送效率</a>");
document.writeln("                <li><a href=\'#\'>服务费用</a>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("         <div class=\'footer_ul\'>");
document.writeln("        	<ul>");
document.writeln("            	<span class=\'footer_ulTwo\'>关于我们</span>");
document.writeln("                <li><a href=\'#\'>招贤纳士</a>");
document.writeln("                <li><a href=\'#\'>网站介绍</a>");
document.writeln("                <li><a href=\'#\'>配送效率</a>");
document.writeln("                <li><a href=\'#\'>商家加盟</a>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("         <div class=\'footer_ul\'>");
document.writeln("        	<ul>");
document.writeln("            	<span class=\'footer_ulThree\'>帮助中心</span>");
document.writeln("                <li><a href=\'#\'>服务内容</a>");
document.writeln("                <li><a href=\'#\'>服务介绍</a>");
document.writeln("                <li><a href=\'#\'>常见问题</a>");
document.writeln("                <li><a href=\'#\'>网站地图</a>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'copyright\'>");
document.writeln("    	<p>© 版权所有 2016 DeathGhost 技术支持：DeathGhost</p>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("<script type=\'text/javascript\' src=\'js/jquery-3.1.0.min.js\'></script>");
document.writeln("</html>");
document.writeln("");