document.writeln("<!DOCTYPE html PUBLIC \'-//W3C//DTD XHTML 1.0 Transitional//EN\' \'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\'>");
document.writeln("<html xmlns=\'http://www.w3.org/1999/xhtml\'>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\' />");
document.writeln("<title>韩师外卖</title>");
document.writeln("<link rel=\'stylesheet\' href=\'css/common.css\' />");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<!--顶部菜单开始-->");
document.writeln("<div class=\'topMenu\'>");
document.writeln("	<div class=\'topNav\'>");
document.writeln("		<div class=\'leftNav\'>");
document.writeln("    		<a href=\'register.html\'>注册</a>/<a class=\'login\' href=\'javascript:void(0)\'>登录</a>");
document.writeln("            <a href=\'#\'>QQ客服</a><a href=\'#\'>微信客服</a><a href=\'#\'>手机客户端</a>");
document.writeln("    	</div>");
document.writeln("   		<div class=\'rightNav\'>");
document.writeln("    		<a href=\'#\'>用户中心</a><a href=\'#\'>我的订单</a><a class=\'ada\' href=\'#\'>购物车（<span></span>）</a><a href=\'#\'>我的收藏</a><a href=\'#\'>商家入驻</a>");
document.writeln("    	</div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<!--顶部菜单结束-->");
document.writeln("<!--登录搜索开始-->");
document.writeln("<div class=\'logo_search\'>");
document.writeln("	<div class=\'logo\'>");
document.writeln("    	<img src=\'image/logo.jpg\' />");
document.writeln("        <i></i>");
document.writeln("        <span>潮州市 [<a href=\'#\'> 湘桥区</a> ]</span>");
document.writeln("    </div>");
document.writeln("    <div class=\'search\'>");
document.writeln("    	<form id=\'main_serach\' method=\'get\' action=\'\'>");
document.writeln("        	<a class=\'main_serachbg\' href=\'#\'>餐厅</a>");
document.writeln("            <a href=\'#\'>食物名</a>");
document.writeln("            <div class=\'search_area\'>");
document.writeln("            <input id=\'skeyword\' type=\'text\' placeholder=\'请输入您所需查找的餐厅名称或食物名称...\' name=\'keyword\' />");
document.writeln("            <input class=\'search_button\' type=\'button\' value=\'搜索\' />");
document.writeln("            </div>");
document.writeln("        </form>");
document.writeln("        <div class=\'search_word\'>");
document.writeln("        	<a href=\'#\'>酸辣土豆丝</a>");
document.writeln("            <a href=\'#\'>螃蟹炒年糕</a>");
document.writeln("            <a href=\'#\'>牛奶炖蛋</a>");
document.writeln("            <a href=\'#\'>芝麻酱凉面</a>");
document.writeln("            <a href=\'#\'>滑蛋虾仁</a>");
document.writeln("            <a href=\'#\'>蒜汁茄子</a>");
document.writeln("        </div>");
document.writeln("   	</div>");
document.writeln("</div>");
document.writeln("<!--登录搜索结束-->");
document.writeln("<!--菜单栏开始-->");
document.writeln("<div class=\'menubg\'>");
document.writeln("	<div class=\'menu\'>");
document.writeln("    	<ul>");
document.writeln("        	<li><a href=\'index.html\'>首页</a></li>");
document.writeln("            <li><a href=\'order.html\'>订餐</a></li>");
document.writeln("            <li><a href=\'credit.html\'>积分商城</a></li>");
document.writeln("            <li><a href=\'aboutUs.html\'>关于我们</a></li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<!--菜单栏结束-->");
document.writeln("");
document.writeln("");
document.writeln("<!--Login登录框-->");
document.writeln(" <div id=\'Login\'>");
document.writeln("	<div id=\'title\'>用户登录<a href=\'#\' class=\'close\'></a></div>");
document.writeln("	<p class=\'des\'>尊敬的会员，欢迎你登录我们的网站，期望你点食愉快");
document.writeln("    </p>");
document.writeln("    ");
document.writeln("    <div id=\'LgCon\'>");
document.writeln("    	<form>");
document.writeln("        	<p class=\'txt\'>登录<input type=\'text\'></p>");
document.writeln("            <p class=\'txt\'>密码<input type=\'text\'></p>");
document.writeln("            <p class=\'ck\'><input type=\'checkbox\'> 下次自动登录</p>");
document.writeln("            <p class=\'but\'><input type=\'submit\' value=\'用户登录\'></p>");
document.writeln("        </form>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\'Layer\'></div>");
document.writeln("<!--Login结束-->");
document.writeln("</body>");
document.writeln("<script type=\'text/javascript\' src=\'js/jquery-3.1.0.min.js\'></script>");
document.writeln("<script type=\'text/javascript\' src=\'js/common.js\'></script>");
document.writeln("</html>");
document.writeln("");